/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabrmi;

import javax.swing.ButtonModel;

/**
 *
 * @author tiagosr
 */
public class FrmInicial extends javax.swing.JFrame {

    private final int MODO_CLIENTE = 1;
    private final int MODO_SERVIDOR = 2;
    private final int MODO_REGISTRO = 3;
    
    /**
     * Creates new form FrmInicial
     */
    public FrmInicial() {
        initComponents();
        this.groupModo.setSelected(this.radioCliente.getModel(), true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupModo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioServidor = new javax.swing.JRadioButton();
        radioRegistro = new javax.swing.JRadioButton();
        radioCliente = new javax.swing.JRadioButton();
        txtOrigem = new javax.swing.JTextField();
        labelOrigem = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        labelDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDI - Tela Inicial");

        jLabel1.setText("Modo de utilização:");

        groupModo.add(radioServidor);
        radioServidor.setText("Servidor");
        radioServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioServidorActionPerformed(evt);
            }
        });

        groupModo.add(radioRegistro);
        radioRegistro.setText("Registro");
        radioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRegistroActionPerformed(evt);
            }
        });

        groupModo.add(radioCliente);
        radioCliente.setText("Cliente");
        radioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClienteActionPerformed(evt);
            }
        });

        txtOrigem.setText("localhost");

        labelOrigem.setText("Endereço IP local:");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        labelDestino.setText("Endereço IP registro:");

        txtDestino.setText("localhost");

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel3.setText("Obs:  Iniciar registro antes do servidor");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelOrigem)
                    .addComponent(labelDestino)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(radioCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(radioServidor)
                            .addGap(18, 18, 18)
                            .addComponent(radioRegistro))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCliente)
                    .addComponent(radioServidor)
                    .addComponent(radioRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(labelOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioServidorActionPerformed
        this.defineModo(MODO_SERVIDOR);
    }//GEN-LAST:event_radioServidorActionPerformed

    private void radioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClienteActionPerformed
        this.defineModo(MODO_CLIENTE);
    }//GEN-LAST:event_radioClienteActionPerformed

    private void radioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRegistroActionPerformed
        this.defineModo(MODO_REGISTRO);
    }//GEN-LAST:event_radioRegistroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        ButtonModel selecao = this.groupModo.getSelection();
        if(selecao == this.radioCliente.getModel()){
            FrmBancoCliente janela = new FrmBancoCliente(this.txtDestino.getText());
            janela.setVisible(true);
        }
        
        if(selecao == this.radioServidor.getModel()){
            FrmServidor servidor = new FrmServidor("Servidor");
            servidor.setVisible(true);
            //Criar Instancia dos servidores
        }
        
        if(selecao == this.radioRegistro.getModel()){
            FrmServidor servidor = new FrmServidor("Servidor de registro");
            servidor.setVisible(true);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void defineModo(int modo){
        switch(modo){
            case MODO_CLIENTE:
                this.txtOrigem.setEditable(false);
                this.txtDestino.setEditable(true);
            break;
            case MODO_SERVIDOR:
                this.txtOrigem.setEditable(true);
                this.txtDestino.setEditable(true);
            break;
            case MODO_REGISTRO:
                this.txtOrigem.setEditable(true);
                this.txtDestino.setEditable(false);
            break;   
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.ButtonGroup groupModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelOrigem;
    private javax.swing.JRadioButton radioCliente;
    private javax.swing.JRadioButton radioRegistro;
    private javax.swing.JRadioButton radioServidor;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigem;
    // End of variables declaration//GEN-END:variables
}
