/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabrmi;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.logging.Level;
import java.util.logging.Logger;
import trabrmi.servidor.InstanciaBancoServidor;
import trabrmi.servidor.RegistroNomesServidor;

/**
 *
 * @author tiagosr
 */
public class FrmServidor extends javax.swing.JFrame {
    private final int MODO_SERVIDOR = 2, MODO_REGISTRO = 3;
    private RegistroNomesServidor registroNomes;
    private InstanciaBancoServidor instanciaBanco;
    private Thread threadServidor;
    /**
     * Creates new form FrmServidor
     */
    public FrmServidor(int modo, String endRegistro, String endLocal) {
        String nome = "Um erro";
        
        initComponents();
        
        try {
            LocateRegistry.createRegistry(1099);
            System.setProperty("java.rmi.server.hostname", "endLocal");
            switch(modo){
                case MODO_SERVIDOR:
                    nome = "Servidor";
                    instanciaBanco = new InstanciaBancoServidor(endRegistro, endLocal);
                    threadServidor = new Thread(instanciaBanco);
                    threadServidor.start();
                break;
                case MODO_REGISTRO:
                    nome = "Servidor de registro";
                    registroNomes = new RegistroNomesServidor(endLocal);
                break;
            }  
        } catch (RemoteException ex) {
            Logger.getLogger(FrmServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.labelAviso.setText(nome+" em execução!");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAviso = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");

        labelAviso.setText("Em execução!");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(labelAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(179, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel labelAviso;
    // End of variables declaration//GEN-END:variables
}
